# Generated by Django 3.2.20 on 2023-08-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerprofile',
            name='image',
            field=models.ImageField(default='default_profile.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='default_profile.png', upload_to='images/'),
        ),
    ]
