# Generated by Django 3.2.20 on 2023-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=256)),
                ('model_name', models.CharField(max_length=256)),
                ('model_code', models.CharField(max_length=256)),
                ('manufacturing_date', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('battery_capacity', models.IntegerField()),
                ('memory_amount', models.IntegerField()),
                ('point', models.IntegerField()),
            ],
        ),
    ]
