# Generated by Django 3.2.20 on 2023-08-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
