# Generated by Django 3.2.20 on 2023-08-09 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('reward', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('regist_start_at', models.DateTimeField()),
                ('regist_end_at', models.DateTimeField()),
                ('activity_start_at', models.DateTimeField()),
                ('activity_end_at', models.DateTimeField()),
                ('subscriber_limit', models.IntegerField()),
                ('subscriber_num', models.IntegerField(default=0)),
                ('activity_category', models.CharField(blank=True, choices=[('kiosk', '키오스크'), ('app_payment', '앱 결제'), ('bank_transfer', '계좌 이체')], max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ManyToManyField(related_name='program', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
