# Generated by Django 3.2.20 on 2023-08-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='subscriber_num',
        ),
    ]
