# Generated by Django 3.2.20 on 2023-08-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_remove_program_subscriber_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='activity_end_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='activity_start_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='regist_end_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='regist_start_at',
            field=models.DateField(),
        ),
    ]
