# Generated by Django 3.2.20 on 2023-08-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20230812_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
